version: '3.1'

services:
#  nginx-proxy:
#    image: nginxproxy/nginx-proxy:latest
#    container_name: nginx-proxy
#    restart: always
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - /home/miami/nginx-proxy/vhost.d:/etc/nginx/vhost.d
#      - /home/miami/nginx-proxy/html:/usr/share/nginx/html
#      - /home/miami/nginx-proxy/certs:/etc/nginx/certs
#      - /var/run/docker.sock:/tmp/docker.sock:ro
#
#  nginx-letsencrypt:
#    image: nginxproxy/acme-companion:latest
#    container_name: nginx-letsencrypt
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#      - /home/miami/nginx-proxy/vhost.d:/etc/nginx/vhost.d
#      - /home/miami/nginx-proxy/html:/usr/share/nginx/html
#      - /home/miami/nginx-proxy/certs:/etc/nginx/certs
#      - /home/miami/nginx-proxy/acme:/etc/acme.sh
#    environment:
#      - DEFAULT_EMAIL=admin@miamitrade.pro
#      - NGINX_PROXY_CONTAINER=nginx-proxy
#    restart: always

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB_FILE=/run/secrets/MIAMI_POSTGRES_DB
      - POSTGRES_USER_FILE=/run/secrets/MIAMI_POSTGRES_USER
      - POSTGRES_PASSWORD_FILE=/run/secrets/MIAMI_POSTGRES_PASSWORD
    secrets:
      - MIAMI_POSTGRES_DB
      - MIAMI_POSTGRES_USER
      - MIAMI_POSTGRES_PASSWORD
    volumes:
      - /home/miami/postgres:/var/lib/postgresql/data

  backend:
    image: ghcr.io/axadiw/miami-backend:latest
    secrets:
      - MIAMI_POSTGRES_DB
      - MIAMI_POSTGRES_USER
      - MIAMI_POSTGRES_PASSWORD
      - MIAMI_FLASK_SECRET
    ports:
      - "5000:5000"
    networks:
      - frontend
    environment:
      - VIRTUAL_HOST=api.miamitrade.pro
      - LETSENCRYPT_HOST=api.miamitrade.pro
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_EMAIL=admin@miamitrade.pro
secrets:
  MIAMI_POSTGRES_PASSWORD:
    external: true
  MIAMI_POSTGRES_DB:
    external: true
  MIAMI_POSTGRES_USER:
    external: true
  MIAMI_FLASK_SECRET:
    external: true