version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB_FILE=/run/secrets/MIAMI_POSTGRES_DB
      - POSTGRES_USER_FILE=/run/secrets/MIAMI_POSTGRES_USER
      - POSTGRES_PASSWORD_FILE=/run/secrets/MIAMI_POSTGRES_PASSWORD
    secrets:
      - MIAMI_POSTGRES_DB
      - MIAMI_POSTGRES_USER
      - MIAMI_POSTGRES_PASSWORD
    volumes:
      - /home/miami/postgres:/var/lib/postgresql/data

  frontend:
    image: ghcr.io/axadiw/miami-frontend:latest
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.miami-frontend.rule=Host(`miamitrade.pro`, `www.miamitrade.pro`)"
        - "traefik.http.routers.miami-frontend.entrypoints=http"
        - "traefik.http.routers.miami-frontend.middlewares=https-redirect"
        - "traefik.http.routers.miami-frontend-https.rule=Host(`miamitrade.pro`, `www.miamitrade.pro`)"
        - "traefik.http.routers.miami-frontend-https.entrypoints=https"
        - "traefik.http.routers.miami-frontend-https.tls=true"
        - "traefik.http.routers.miami-frontend-https.tls.certresolver=le"
        - "traefik.docker.network=traefik-public"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.services.miami-frontend-https.loadbalancer.server.port=80"


  backend:
    image: ghcr.io/axadiw/miami-backend:latest
    secrets:
      - MIAMI_POSTGRES_DB
      - MIAMI_POSTGRES_USER
      - MIAMI_POSTGRES_PASSWORD
      - MIAMI_FLASK_SECRET
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.miami-backend.rule=Host(`api.miamitrade.pro`)"
        - "traefik.http.routers.miami-backend.entrypoints=http"
        - "traefik.http.routers.miami-backend.middlewares=https-redirect"
        - "traefik.http.routers.miami-backend-https.rule=Host(`api.miamitrade.pro`)"
        - "traefik.http.routers.miami-backend-https.entrypoints=https"

        - "traefik.http.routers.miami-backend-https.tls=true"
        - "traefik.http.routers.miami-backend-https.tls.certresolver=le"
        - "traefik.docker.network=traefik-public"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.services.miami-backend-https.loadbalancer.server.port=5000"

networks:
  traefik-public:
    external: true

secrets:
  MIAMI_POSTGRES_PASSWORD:
    external: true
  MIAMI_POSTGRES_DB:
    external: true
  MIAMI_POSTGRES_USER:
    external: true
  MIAMI_FLASK_SECRET:
    external: true