version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB_FILE=/run/secrets/MIAMI_POSTGRES_DB
      - POSTGRES_USER_FILE=/run/secrets/MIAMI_POSTGRES_USER
      - POSTGRES_PASSWORD_FILE=/run/secrets/MIAMI_POSTGRES_PASSWORD
    secrets:
      - MIAMI_POSTGRES_DB
      - MIAMI_POSTGRES_USER
      - MIAMI_POSTGRES_PASSWORD
    volumes:
      - /home/miami/postgres:/var/lib/postgresql/data

  backend:
    image: ghcr.io/axadiw/miami-backend:latest
    secrets:
      - MIAMI_POSTGRES_DB
      - MIAMI_POSTGRES_USER
      - MIAMI_POSTGRES_PASSWORD
      - MIAMI_FLASK_SECRET
    environment:
      - VIRTUAL_HOST=api.miamitrade.pro
      - LETSENCRYPT_HOST=api.miamitrade.pro
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_EMAIL=admin@miamitrade.pro
    networks:
      - webproxy
networks:
  webproxy:
    external:
      name: webproxy

secrets:
  MIAMI_POSTGRES_PASSWORD:
    external: true
  MIAMI_POSTGRES_DB:
    external: true
  MIAMI_POSTGRES_USER:
    external: true
  MIAMI_FLASK_SECRET:
    external: true