version: '3.1'

services:

  db:
    image: postgres
    environment:
      - POSTGRES_DB_FILE=/run/secrets/MIAMI_POSTGRES_DB
      - POSTGRES_USER_FILE=/run/secrets/MIAMI_POSTGRES_USER
      - POSTGRES_PASSWORD_FILE=/run/secrets/MIAMI_POSTGRES_PASSWORD
      - MIAMI_FLASK_SECRET=/run/secrets/MIAMI_FLASK_SECRET
    secrets:
      - MIAMI_POSTGRES_DB
      - MIAMI_POSTGRES_USER
      - MIAMI_POSTGRES_PASSWORD
      - MIAMI_FLASK_SECRET
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8080:8080

  backend:
    image: alpine
    build:
      context: ./backend
      dockerfile: Dockerfile
    secrets:
      - MIAMI_POSTGRES_DB
      - MIAMI_POSTGRES_USER
      - MIAMI_POSTGRES_PASSWORD
      - MIAMI_FLASK_SECRET

secrets:
  MIAMI_POSTGRES_PASSWORD:
      external: true
  MIAMI_POSTGRES_DB:
    external: true
  MIAMI_POSTGRES_USER:
    external: true
  MIAMI_FLASK_SECRET:
    external: true