version: '3.8'

services:

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB_FILE=/run/secrets/MIAMI_POSTGRES_DB
      - POSTGRES_USER_FILE=/run/secrets/MIAMI_POSTGRES_USER
      - POSTGRES_PASSWORD_FILE=/run/secrets/MIAMI_POSTGRES_PASSWORD
    secrets:
      - MIAMI_POSTGRES_DB
      - MIAMI_POSTGRES_USER
      - MIAMI_POSTGRES_PASSWORD
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 1073741824 #1G
    ports:
      - 5432:5432

secrets:
  MIAMI_POSTGRES_PASSWORD:
    external: true
  MIAMI_POSTGRES_DB:
    external: true
  MIAMI_POSTGRES_USER:
    external: true
  MIAMI_FLASK_SECRET:
    external: true