import multiprocessing

HARVESTER_TYPE_ENVIRONMENT_VARIABLE = 'HARVESTER'

MAX_CANDLES_HISTORY_TO_FETCH = 100000
MAX_CONCURRENT_FETCHES = 20
MAX_CONCURRENT_GAPS_CALCULATIONS = multiprocessing.cpu_count()

GLOBAL_QUEUE_START_COMMAND: str = 'START'
GLOBAL_QUEUE_REFRESH_COMMAND: str = 'REFRESH'
