FROM python:3.11 as python-base
ENV POETRY_VERSION=1.6.1
ENV POETRY_HOME=/opt/poetry
ENV POETRY_VENV=/opt/poetry-venv
ENV POETRY_CACHE_DIR=/opt/.cache

FROM python-base as poetry-base
RUN python3 -m venv $POETRY_VENV \
	&& $POETRY_VENV/bin/pip install -U pip setuptools \
	&& $POETRY_VENV/bin/pip install poetry==${POETRY_VERSION}

FROM python-base as runtime
ARG VERSION
ENV MIAMI_VERSION=$VERSION
COPY --from=poetry-base ${POETRY_VENV} ${POETRY_VENV}
ENV PATH="${PATH}:${POETRY_VENV}/bin"
WORKDIR /app
COPY README.md poetry.lock pyproject.toml ./
COPY README.md  ./
RUN poetry check
RUN poetry install --no-interaction --no-cache

COPY harvesting  /app/harvesting
COPY ccxt /app/ccxt
COPY shared /app/shared
COPY ./shared/consts_tpl.py /app/shared/consts_secrets.py
COPY entrypoint_data_harvester.sh /app
CMD [ "/bin/sh", "entrypoint_data_harvester.sh"]