example_response = {'id': 123, 'version': 2,
                    'account': {'id': 666, 'type': 'bybit_usdt_perpetual', 'name': 'My Bybit',
                                'market': 'Bybit Futures USDT Perpetual', 'link': '/accounts/666'},
                    'pair': 'USDT_BTCUSDT', 'instant': False,
                    'status': {'type': 'created', 'basic_type': 'created', 'title': 'Pending'},
                    'leverage': {'enabled': False},
                    'position': {'type': 'buy', 'editable': False, 'units': {'value': '10', 'editable': False},
                                 'price': {'value': '6.0', 'value_without_commission': '5.0', 'editable': True},
                                 'total': {'value': '100.0'}, 'order_type': 'market',
                                 'status': {'type': 'order_placed', 'basic_type': 'order_placed', 'title': 'Placed'}},
                    'take_profit': {'enabled': True, 'price_type': 'value', 'steps': [
                        {'id': 711497167, 'order_type': 'limit', 'editable': True, 'units': {'value': None},
                         'price': {'type': 'bid', 'value': '10.0', 'percent': None}, 'volume': '30.0', 'total': None,
                         'trailing': {'enabled': False, 'percent': None},
                         'status': {'type': 'idle', 'basic_type': 'idle', 'title': 'Pending'},
                         'data': {'cancelable': True, 'panic_sell_available': False}, 'position': 1},
                        {'id': 711497168, 'order_type': 'limit', 'editable': True, 'units': {'value': None},
                         'price': {'type': 'bid', 'value': '20.0', 'percent': None}, 'volume': '70.0', 'total': None,
                         'trailing': {'enabled': False, 'percent': None},
                         'status': {'type': 'idle', 'basic_type': 'idle', 'title': 'Pending'},
                         'data': {'cancelable': True, 'panic_sell_available': False}, 'position': 2},
                    ]},
                    'stop_loss': {'enabled': True, 'price_type': 'value', 'breakeven': True, 'order_type': 'market',
                                  'editable': True, 'price': {'value': None, 'percent': None},
                                  'conditional': {'price': {'value': '5.0', 'type': 'bid', 'percent': None},
                                                  'trailing': {'enabled': False, 'percent': None}},
                                  'timeout': {'enabled': True, 'value': 60},
                                  'status': {'type': 'idle', 'basic_type': 'idle', 'title': 'Pending'}},
                    'reduce_funds': {'steps': []}, 'market_close': {}, 'note': '', 'note_raw': None,
                    'skip_enter_step': False, 'data': {'editable': False,
                                                       'current_price': {'bid': '67989.8', 'ask': '67989.9',
                                                                         'last': '67991.9',
                                                                         'quote_volume': '9050126531.8672',
                                                                         'day_change_percent': '0.035956'},
                                                       'target_price_type': 'price', 'orderbook_price_currency': 'USDT',
                                                       'base_order_finished': True, 'missing_funds_to_close': '0.0',
                                                       'liquidation_price': None, 'average_enter_price': None,
                                                       'average_close_price': None,
                                                       'average_enter_price_without_commission': None,
                                                       'average_close_price_without_commission': None,
                                                       'panic_sell_available': False, 'add_funds_available': False,
                                                       'reduce_funds_available': False, 'force_start_available': True,
                                                       'force_process_available': True, 'cancel_available': False,
                                                       'finished': False, 'base_position_step_finished': False,
                                                       'entered_amount': '0.0', 'entered_total': '0.0',
                                                       'closed_amount': '0.0', 'closed_total': '0.0',
                                                       'commission': 0.0006, 'created_at': '2024-04-04T21:13:37.782Z',
                                                       'updated_at': '2024-04-04T21:13:37.782Z', 'type': 'smart_trade'},
                    'profit': {'volume': None, 'usd': None, 'percent': '0.0', 'roe': None},
                    'margin': {'amount': None, 'total': None}, 'is_position_not_filled': True}
