"""Added LastFetchedDate

Revision ID: 9b99ae6e607f
Revises: 37b956ef4ec2
Create Date: 2023-12-10 00:39:27.887845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b99ae6e607f'
down_revision: Union[str, None] = '37b956ef4ec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SkippedGaps')
    op.create_table('LastFetchedDates',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('symbol', sa.Integer(), nullable=False),
                    sa.Column('exchange', sa.Integer(), nullable=False),
                    sa.Column('timeframe', sa.Integer(), nullable=False),
                    sa.Column('last_fetched', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['symbol'], ['Symbols.id'], ),
                    sa.ForeignKeyConstraint(['exchange'], ['Exchanges.id'], ),
                    sa.ForeignKeyConstraint(['timeframe'], ['Timeframes.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    )
    with op.batch_alter_table("LastFetchedDates") as batch_op:
        batch_op.create_unique_constraint('lastfetcheddates_unique_sett',
                                          ['symbol', 'exchange', 'timeframe'])


def downgrade() -> None:
    op.drop_table('LastFetchedDates')
