name: [Backend] Build & Deploy
on:
  push:
    branches: [master]
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: cache poetry install
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-1.5.1
      - uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: cache deps
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: .venv
          key: pydeps-${{ hashFiles('**/poetry.lock') }}
      - run: poetry install --no-interaction --no-root
        if: steps.cache-deps.outputs.cache-hit != 'true'
      - run: poetry install --no-interaction
      - run: cp consts_tpl.py consts_secrets.py
      - run: poetry run python -m pytest

  publish_and_deploy:
    if: github.event_name == 'push' && contains(github.event.ref, '/tags/')
    defaults:
      run:
        working-directory: ./backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image (latest)
        run: |
          docker build . --tag ghcr.io/axadiw/miami-backend:latest
          docker push ghcr.io/axadiw/miami-backend:latest
      - name: Build the Docker image (tag version)
        run: |
          docker build . --tag ghcr.io/axadiw/miami-backend:${{  github.ref_name }}"
          docker push ghcr.io/axadiw/miami-backend:${{  github.ref_name }}"
      - name: Deploy to remote server
        uses: sagebind/docker-swarm-deploy-action@v2
        with:
          remote_host: ${{ secrets.REMOTE_HOST }}
          ssh_private_key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.REMOTE_PUBLIC_KEY }}
          args: stack deploy --with-registry-auth --compose-file docker-compose-prod.yml miami