name: Build
on:
  push:
    branches: [ master ]
    tags:
      - '*'
jobs:
  backend_test:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - name: cache poetry install
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-1.6.1
      - uses: snok/install-poetry@v1
        with:
          version: 1.6.1
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: cache deps
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: .venv
          key: pydeps-${{ hashFiles('**/poetry.lock') }}
      - run: poetry install --no-interaction --no-root
        if: steps.cache-deps.outputs.cache-hit != 'true'
      - run: poetry install --no-interaction
      - run: cp shared/consts_tpl.py shared/consts_secrets.py
      - run: poetry run python -m pytest

  frontend_test:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  api_build_and_publish:
    if: github.event_name == 'push' && contains(github.event.ref, '/tags/')
    defaults:
      run:
        working-directory: ./backend
    runs-on: self-hosted
    needs: [ backend_test ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image (latest)
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile_api
          platforms: linux/aarch64
          build-args: |
            VERSION=${{ github.ref_name }}
          push: true
          tags: ghcr.io/axadiw/miami-api:latest
      - name: Build the Docker image (tag version)
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile_api
          platforms: linux/aarch64
          build-args: |
            VERSION=${{ github.ref_name }}
          push: true
          tags: ghcr.io/axadiw/miami-api:${{  github.ref_name }}

  data_harvester_build_and_publish:
    if: github.event_name == 'push' && contains(github.event.ref, '/tags/')
    defaults:
      run:
        working-directory: ./backend
    runs-on: self-hosted
    needs: [ backend_test ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image (latest)
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile_data_harvester
          platforms: linux/aarch64
          build-args: |
            VERSION=${{ github.ref_name }}
          push: true
          tags: ghcr.io/axadiw/miami-data-harvester:latest
      - name: Build the Docker image (tag version)
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile_data_harvester
          platforms: linux/aarch64
          build-args: |
            VERSION=${{ github.ref_name }}
          push: true
          tags: ghcr.io/axadiw/miami-data-harvester:${{  github.ref_name }}

  frontend_build_and_publish:
    if: github.event_name == 'push' && contains(github.event.ref, '/tags/')
    defaults:
      run:
        working-directory: ./frontend
    runs-on: self-hosted
    needs: [ frontend_test ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image (latest)
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          platforms: linux/aarch64
          push: true
          tags: ghcr.io/axadiw/miami-frontend:latest
      - name: Build the Docker image (tag version)
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          platforms: linux/aarch64
          push: true
          tags: ghcr.io/axadiw/miami-frontend:${{  github.ref_name }}

  deploy:
    defaults:
      run:
        working-directory: ./frontend
    runs-on: self-hosted
    needs: [ frontend_build_and_publish, api_build_and_publish, data_harvester_build_and_publish ]
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to remote server
        uses: kitconcept/docker-stack-deploy@v1.0.1
        with:
          registry: "ghcr.io"
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USERNAME }}
          remote_private_key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          stack_file: "docker-compose-prod.yml"
          stack_name: ${{ secrets.REMOTE_STACK_NAME }}
      - name: pushover-actions
        uses: umahmood/pushover-actions@main
        env:
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
        with:
          status: ${{ job.status }}
          title: 'Miami Deployment'
          message: 'Deploy ${{  github.ref_name }} successful'