name: Build release
on:
  push:
    tags:
      - '*'
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  build:
    defaults:
      run:
        working-directory: ./backend    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)


  publish:
    defaults:
      run:
        working-directory: ./backend  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: |
           docker build . --tag ghcr.io/axadiw/miami:latest
           docker push ghcr.io/axadiw/miami:latest
