name: Frontend - Build & Publish
on:
  workflow_run:
    workflows: [Frontend Test]
    types:
      - completed
  push:
    tags:
      - '*'

jobs:
  build_and_publish:
    defaults:
      run:
        working-directory: ./frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image (latest)
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          platforms: linux/aarch64
          push: true
          tags: ghcr.io/axadiw/miami-frontend:latest
      - name: Build the Docker image (tag version)
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          platforms: linux/aarch64
          push: true
          tags: ghcr.io/axadiw/miami-frontend:${{  github.ref_name }}